/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HizmetlerIndexRouteImport } from './routes/hizmetler.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerIndexRoute = HizmetlerIndexRouteImport.update({
  id: '/hizmetler/',
  path: '/hizmetler/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hizmetler/': typeof HizmetlerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hizmetler': typeof HizmetlerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hizmetler/': typeof HizmetlerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hizmetler/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hizmetler'
  id: '__root__' | '/' | '/hizmetler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HizmetlerIndexRoute: typeof HizmetlerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler/': {
      id: '/hizmetler/'
      path: '/hizmetler'
      fullPath: '/hizmetler/'
      preLoaderRoute: typeof HizmetlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HizmetlerIndexRoute: HizmetlerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
