/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SssRouteImport } from './routes/sss'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HijyenRouteImport } from './routes/hijyen'
import { Route as HakkimdaRouteImport } from './routes/hakkimda'
import { Route as CalismalarRouteImport } from './routes/calismalar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HizmetlerIndexRouteImport } from './routes/hizmetler.index'
import { Route as HizmetlerSlugRouteImport } from './routes/hizmetler.$slug'

const SssRoute = SssRouteImport.update({
  id: '/sss',
  path: '/sss',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HijyenRoute = HijyenRouteImport.update({
  id: '/hijyen',
  path: '/hijyen',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimdaRoute = HakkimdaRouteImport.update({
  id: '/hakkimda',
  path: '/hakkimda',
  getParentRoute: () => rootRouteImport,
} as any)
const CalismalarRoute = CalismalarRouteImport.update({
  id: '/calismalar',
  path: '/calismalar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerIndexRoute = HizmetlerIndexRouteImport.update({
  id: '/hizmetler/',
  path: '/hizmetler/',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerSlugRoute = HizmetlerSlugRouteImport.update({
  id: '/hizmetler/$slug',
  path: '/hizmetler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calismalar': typeof CalismalarRoute
  '/hakkimda': typeof HakkimdaRoute
  '/hijyen': typeof HijyenRoute
  '/iletisim': typeof IletisimRoute
  '/sss': typeof SssRoute
  '/hizmetler/$slug': typeof HizmetlerSlugRoute
  '/hizmetler/': typeof HizmetlerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calismalar': typeof CalismalarRoute
  '/hakkimda': typeof HakkimdaRoute
  '/hijyen': typeof HijyenRoute
  '/iletisim': typeof IletisimRoute
  '/sss': typeof SssRoute
  '/hizmetler/$slug': typeof HizmetlerSlugRoute
  '/hizmetler': typeof HizmetlerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calismalar': typeof CalismalarRoute
  '/hakkimda': typeof HakkimdaRoute
  '/hijyen': typeof HijyenRoute
  '/iletisim': typeof IletisimRoute
  '/sss': typeof SssRoute
  '/hizmetler/$slug': typeof HizmetlerSlugRoute
  '/hizmetler/': typeof HizmetlerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calismalar'
    | '/hakkimda'
    | '/hijyen'
    | '/iletisim'
    | '/sss'
    | '/hizmetler/$slug'
    | '/hizmetler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calismalar'
    | '/hakkimda'
    | '/hijyen'
    | '/iletisim'
    | '/sss'
    | '/hizmetler/$slug'
    | '/hizmetler'
  id:
    | '__root__'
    | '/'
    | '/calismalar'
    | '/hakkimda'
    | '/hijyen'
    | '/iletisim'
    | '/sss'
    | '/hizmetler/$slug'
    | '/hizmetler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalismalarRoute: typeof CalismalarRoute
  HakkimdaRoute: typeof HakkimdaRoute
  HijyenRoute: typeof HijyenRoute
  IletisimRoute: typeof IletisimRoute
  SssRoute: typeof SssRoute
  HizmetlerSlugRoute: typeof HizmetlerSlugRoute
  HizmetlerIndexRoute: typeof HizmetlerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sss': {
      id: '/sss'
      path: '/sss'
      fullPath: '/sss'
      preLoaderRoute: typeof SssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hijyen': {
      id: '/hijyen'
      path: '/hijyen'
      fullPath: '/hijyen'
      preLoaderRoute: typeof HijyenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimda': {
      id: '/hakkimda'
      path: '/hakkimda'
      fullPath: '/hakkimda'
      preLoaderRoute: typeof HakkimdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calismalar': {
      id: '/calismalar'
      path: '/calismalar'
      fullPath: '/calismalar'
      preLoaderRoute: typeof CalismalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler/': {
      id: '/hizmetler/'
      path: '/hizmetler'
      fullPath: '/hizmetler/'
      preLoaderRoute: typeof HizmetlerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler/$slug': {
      id: '/hizmetler/$slug'
      path: '/hizmetler/$slug'
      fullPath: '/hizmetler/$slug'
      preLoaderRoute: typeof HizmetlerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalismalarRoute: CalismalarRoute,
  HakkimdaRoute: HakkimdaRoute,
  HijyenRoute: HijyenRoute,
  IletisimRoute: IletisimRoute,
  SssRoute: SssRoute,
  HizmetlerSlugRoute: HizmetlerSlugRoute,
  HizmetlerIndexRoute: HizmetlerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
